config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'landing/index'

  resources :articles
  resources :users
  resources :authors

  root controller: :landing, action: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title,  presence: true
  validates :content, presence: true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, presence: :true
  validates :genre, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :password, presence: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    # flash[:notice] = "Article was successfully deleted."
    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @author = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    @author.save
    redirect_to @author
  end

  private
  def author_params
    params.require(:author).permit(:name, :genre)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @articles = Article.all
    @authors = Author.all
  end

  # def index
  #   
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_with(model: @article, local: true) do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', root_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>


<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', root_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= form_with scope: :author, url: authors_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :genre %><br>
    <%= form.text_area :genre %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/authors/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>
 
<p>
  <strong>Genre:</strong>
  <%= @author.genre %>
</p>

<%= link_to 'Back', root_path %>

app/views/landing/index.html.erb
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= article.title %><br />
      <%= article.content %><br />
      <%= link_to 'Show', article_path(article) %><br />
      <%= link_to 'Edit', edit_article_path(article) %>
      <%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Article', new_article_path %>

<ul>
  <% @authors.each do |author|%>
    <li>
      <%= author.name %><br />
      <%= author.genre %><br />
      <%= link_to 'Show', author_path(author) %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Author', new_author_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>